import './globals.css';

import { AntdRegistry } from '@ant-design/nextjs-registry';
import { App, ConfigProvider } from 'antd';
import type { Metadata } from 'next';
import { Nunito, Nunito_Sans } from 'next/font/google';
import React from 'react';

import { Transition } from '@/lib/motion';
import { themeConfig } from '@/lib/theme/antd';

const nunito = Nunito({
  variable: '--font-nunito',
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

const nunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Daily Running',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} ${nunitoSans.variable}`}>
        <AntdRegistry>
          <ConfigProvider theme={themeConfig}>
            <App>
              <Transition>{children}</Transition>
            </App>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
